// Vercel Routing Middleware — runs before cache on every matched request.
//
// Apex (`narraterx.ai` / `www.narraterx.ai`):
//   - `/` → rewrite to `/landing.html` (static marketing home)
//   - Known marketing paths (e.g. `/how-it-works`, `/features`, `/demo`,
//     `/pricing`, `/who-its-for`, `/why`, `/about`) → rewrite to their
//     `.html` files so they don't fall through to the SPA fallback in
//     vercel.json. Trailing slashes tolerated.
//   - Everything else (e.g. `/onboard`) → pass through; the SPA fallback
//     serves the React onboarding wizard.
//
// Subdomain (`<slug>.narraterx.ai`):
//   - 404 if the slug doesn't match an active workspace
//   - Pass through otherwise (the React app handles routing)
//
// Per-endpoint workspace data is fetched by api/_lib/workspaceContext.js,
// which also extracts the slug. Middleware does NOT inject workspace
// headers — that pattern doesn't propagate through this Vite/Edge setup.
//
// Dual-run safe: when MULTITENANT_DATABASE_URL is unset (legacy per-brand
// Vercel projects: narraterx-people, narraterx-equine, narraterx-animals),
// the middleware no-ops and every request passes through unchanged.

import { next, rewrite } from '@vercel/functions'

export const config = {
  runtime: 'nodejs',
  matcher: ['/((?!assets/|favicon\\.ico|robots\\.txt|sitemap\\.xml|_vercel/).*)'],
}

const APEX_HOSTS = new Set(['narraterx.ai', 'www.narraterx.ai'])

// Clean-URL routing table for the marketing site. Keys are the public path
// (no trailing slash, lowercase); values are the static file inside public/.
// Keep this in sync with the actual files in `public/` — adding a new page
// requires both a file AND a row here, otherwise the SPA fallback eats it.
const MARKETING_PATHS = {
  '/how-it-works': '/how-it-works.html',
  '/features':     '/features.html',
  '/demo':         '/demo.html',
  '/pricing':      '/pricing.html',
  '/who-its-for':  '/who-its-for.html',
  '/why':          '/why.html',
  '/about':        '/about.html',
  '/compare':      '/compare.html',
  '/vs':           '/compare.html',
  '/transparency': '/transparency.html',
  // Design mock variants of the home page. Linked from /mocks.
  '/mocks':            '/mocks.html',
  '/mock-warm':        '/mock-warm.html',
  '/mock-bold':        '/mock-bold.html',
  '/mock-clinical':    '/mock-clinical.html',
  '/mock-dark':        '/mock-dark.html',
  '/mock-dusk':            '/mock-dusk.html',
  '/mock-dusk-midnight':   '/mock-dusk-midnight.html',
  '/mock-dusk-forest':     '/mock-dusk-forest.html',
  '/mock-dusk-parchment':  '/mock-dusk-parchment.html',
}

function extractSlug(host) {
  if (!host) return null
  const h = host.split(':')[0].toLowerCase()
  if (APEX_HOSTS.has(h)) return null
  if (h.endsWith('.narraterx.ai')) {
    return h.slice(0, -'.narraterx.ai'.length)
  }
  return null
}

async function workspaceExists(slug, supabaseUrl, supabaseKey) {
  const url = `${supabaseUrl}/rest/v1/workspaces?slug=eq.${encodeURIComponent(slug)}&select=status&limit=1`
  let r
  try {
    r = await fetch(url, {
      headers: { apikey: supabaseKey, Authorization: `Bearer ${supabaseKey}` },
    })
  } catch (e) {
    console.error('[middleware] workspace lookup network error:', e?.message)
    return false
  }
  if (!r.ok) {
    console.error(`[middleware] workspace lookup failed: ${r.status}`)
    return false
  }
  const rows = await r.json().catch(() => null)
  if (!Array.isArray(rows) || rows.length === 0) return false
  return rows[0].status === 'active'
}

export default async function middleware(request) {
  // Dual-run gate: legacy per-brand Vercel projects pass through unchanged.
  if (!process.env.MULTITENANT_DATABASE_URL) return next()

  const host = request.headers.get('host') || ''
  const url  = new URL(request.url)
  const slug = extractSlug(host)

  // Apex / www: marketing site.
  if (!slug) {
    const isApex = APEX_HOSTS.has(host.split(':')[0].toLowerCase())
    if (isApex) {
      if (url.pathname === '/') {
        return rewrite(new URL('/landing.html', request.url))
      }
      // Tolerate trailing slash on clean URLs.
      const key = url.pathname.replace(/\/$/, '') || '/'
      const dest = MARKETING_PATHS[key.toLowerCase()]
      if (dest) {
        return rewrite(new URL(dest, request.url))
      }
      // Blog routes: /blog → /blog.html, /blog/<slug> → /blog/<slug>.html.
      // Posts are generated by scripts/build-blog.mjs from src/content/blog/*.md
      // and committed under public/blog/. Slugs must be lowercase alphanumeric
      // + hyphens; reject anything else so we don't expose internal paths.
      const lower = key.toLowerCase()
      if (lower === '/blog') {
        return rewrite(new URL('/blog.html', request.url))
      }
      const blogMatch = lower.match(/^\/blog\/([a-z0-9][a-z0-9-]*)$/)
      if (blogMatch) {
        return rewrite(new URL(`/blog/${blogMatch[1]}.html`, request.url))
      }
    }
    return next()
  }

  // Subdomain: verify the workspace exists and is active. Phase 1A returns
  // 404 plain text on miss; Phase 1E may redirect to apex onboarding.
  const supabaseUrl = process.env.SUPABASE_URL
  const supabaseKey = process.env.SUPABASE_SERVICE_KEY
  if (!supabaseUrl || !supabaseKey) {
    console.error('[middleware] SUPABASE_URL/SERVICE_KEY not configured')
    return new Response('Workspace lookup unavailable', { status: 503 })
  }

  const exists = await workspaceExists(slug, supabaseUrl, supabaseKey)
  if (!exists) {
    return new Response(`Unknown workspace: ${slug}`, {
      status: 404,
      headers: { 'Content-Type': 'text/plain' },
    })
  }

  return next()
}
